math=int(input("Enter marks in math:"))
science=int(input("Enter marks in science:"))
hindi=int(input("Enter marks in hindi:"))
english=int(input("Enter marks in english:"))
total=int(math+science+hindi+english)
avg=int(total/4)
print("The average marks obtained:",avg)
percentage=int(avg)
print("The total percentage is:", percentage,"%" )